#!/usr/bin/env python3
"""Generate a paper-style GordianBench PDF report with visualizations."""

from __future__ import annotations

import argparse
import json
import textwrap
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages


ROOT = Path(__file__).resolve().parents[1]


@dataclass
class Phase6Model:
    name: str
    rate: float
    counts: dict[str, int]
    tier: str


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _title_page(pdf: PdfPages) -> None:
    fig = plt.figure(figsize=(8.5, 11))
    fig.patch.set_facecolor("white")
    fig.text(0.1, 0.92, "GordianBench: Final Research Report", fontsize=22, weight="bold")
    fig.text(0.1, 0.88, "Phase 4 foundations through Phase 6 capability sweep", fontsize=13)
    fig.text(
        0.1,
        0.82,
        "This artifact replaces dashboard-style presentation with a paper-style\n"
        "narrative report and reproducible figures grounded in oracle-graded results.",
        fontsize=11,
    )
    fig.text(0.1, 0.73, "Core empirical finding", fontsize=14, weight="bold")
    fig.text(
        0.1,
        0.67,
        "On Archetype D (stale-read under recovering-lag), identical conditions produce\n"
        "a three-step gradient: 0% (Haiku/Gemini-2.5) → 40% (Opus/GPT-4.1) → 100% (GPT-5.5).\n"
        "Mechanistic patch inspection ties the frontier split to one ordering detail:\n"
        "post-commit vs in-statement LSN capture.",
        fontsize=11,
    )
    fig.text(
        0.1,
        0.53,
        "Sources: phase_4_report_6.md, phase_5_report_13.md, phase_6_report.md,\n"
        "archetype-d-stale-read/phase6_cells/phase6_headline_rollup.json",
        fontsize=10,
    )
    fig.text(0.1, 0.46, "Generated by scripts/generate_final_report_pdf.py", fontsize=10, style="italic")
    plt.axis("off")
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def _timeline_page(pdf: PdfPages) -> None:
    events = [
        ("2026-06-23", "Phase 4 engineering + live sign-off"),
        ("2026-06-24", "Phase 4 consolidated findings and seam map"),
        ("2026-06-30", "Phase 6 pre-commitments frozen + GPT-5.5 shakedown"),
        ("2026-07-01", "Full 5-cell Phase 6 sweep complete"),
    ]
    y = list(range(len(events), 0, -1))
    x = [1] * len(events)

    fig, ax = plt.subplots(figsize=(8.5, 11))
    ax.scatter(x, y, s=120, color="#1f77b4")
    ax.plot(x, y, color="#1f77b4", linewidth=2)
    for idx, (date, label) in enumerate(events):
        ax.text(1.05, y[idx], f"{date}  {label}", va="center", fontsize=11)
    ax.set_xlim(0.9, 2.6)
    ax.set_ylim(0.5, len(events) + 0.5)
    ax.set_title("Figure 1. Study Timeline", fontsize=16, pad=20)
    ax.axis("off")
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def _phase6_models(rollup: dict) -> list[Phase6Model]:
    tier_map = {
        "gpt-5.5": "Frontier",
        "claude-opus-4-8": "Frontier",
        "claude-haiku-4-5-20251001": "Mid-tier",
        "gemini-2.5-pro": "Mid-tier",
        "gpt-4.1": "Mid-tier",
    }
    out: list[Phase6Model] = []
    for name, payload in rollup["rollup_by_model"].items():
        out.append(
            Phase6Model(
                name=name,
                rate=float(payload["resolution_rate"]),
                counts={k: int(v) for k, v in payload["counts"].items()},
                tier=tier_map.get(name, "Unspecified"),
            )
        )
    order = ["claude-haiku-4-5-20251001", "gemini-2.5-pro", "gpt-4.1", "claude-opus-4-8", "gpt-5.5"]
    return sorted(out, key=lambda m: order.index(m.name) if m.name in order else 99)


def _rates_page(pdf: PdfPages, models: list[Phase6Model]) -> None:
    labels = [m.name for m in models]
    rates = [m.rate * 100 for m in models]
    colors = ["#d62728" if m.tier == "Mid-tier" else "#1f77b4" for m in models]

    fig, ax = plt.subplots(figsize=(11, 6))
    bars = ax.bar(labels, rates, color=colors)
    ax.set_ylim(0, 110)
    ax.set_ylabel("Resolution Rate (%)")
    ax.set_title("Figure 2. Phase 6 Oracle Resolution Rates by Model")
    ax.tick_params(axis="x", rotation=20)
    for b, r in zip(bars, rates):
        ax.text(b.get_x() + b.get_width() / 2, r + 2, f"{r:.0f}%", ha="center", fontsize=10)
    ax.grid(axis="y", alpha=0.25)
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def _stacked_outcomes_page(pdf: PdfPages, models: list[Phase6Model]) -> None:
    labels = [m.name for m in models]
    pass_ct = [m.counts.get("PASS", 0) for m in models]
    cap_ct = [m.counts.get("CAPABILITY_FAIL", 0) for m in models]
    build_ct = [m.counts.get("BUILD_FAIL", 0) for m in models]
    nopatch_ct = [m.counts.get("NO_PATCH", 0) for m in models]

    fig, ax = plt.subplots(figsize=(11, 6))
    ax.bar(labels, pass_ct, label="PASS", color="#2ca02c")
    ax.bar(labels, cap_ct, bottom=pass_ct, label="CAPABILITY_FAIL", color="#d62728")
    bottom2 = [a + b for a, b in zip(pass_ct, cap_ct)]
    ax.bar(labels, build_ct, bottom=bottom2, label="BUILD_FAIL", color="#ff7f0e")
    bottom3 = [a + b for a, b in zip(bottom2, build_ct)]
    ax.bar(labels, nopatch_ct, bottom=bottom3, label="NO_PATCH", color="#9467bd")

    ax.set_ylim(0, 5)
    ax.set_ylabel("Run Count (k=5)")
    ax.set_title("Figure 3. Outcome Composition per Model")
    ax.tick_params(axis="x", rotation=20)
    ax.legend(loc="upper left")
    ax.grid(axis="y", alpha=0.25)
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def _phase4_oracle_page(pdf: PdfPages) -> None:
    models = ["Haiku 4.5", "GPT-4.1"]
    tier1 = [0, 0]
    tier2 = [1, 1]
    x = range(len(models))

    fig, ax = plt.subplots(figsize=(9, 6))
    ax.bar([i - 0.15 for i in x], tier1, width=0.3, label="Tier 1 (Liveness)", color="#ff7f0e")
    ax.bar([i + 0.15 for i in x], tier2, width=0.3, label="Tier 2 (Safety)", color="#1f77b4")
    ax.set_xticks(list(x), models)
    ax.set_ylim(0, 1.2)
    ax.set_ylabel("Score")
    ax.set_title("Figure 4. Phase 4 Tier Decomposition Anchor Runs")
    ax.legend(loc="upper left")
    ax.grid(axis="y", alpha=0.25)
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def _mechanism_page(pdf: PdfPages) -> None:
    labels = ["GPT-5.5 LSN attempts", "Opus LSN attempts"]
    correct_ordering = [3, 0]
    p3_ordering = [0, 3]
    x = range(len(labels))

    fig, ax = plt.subplots(figsize=(9, 6))
    ax.bar(x, correct_ordering, label="Post-commit LSN (correct)", color="#2ca02c")
    ax.bar(x, p3_ordering, bottom=correct_ordering, label="In-statement LSN (P3)", color="#d62728")
    ax.set_xticks(list(x), labels)
    ax.set_ylim(0, 3.5)
    ax.set_ylabel("Count of LSN-shaped patches")
    ax.set_title("Figure 5. Mechanistic Split Behind Frontier Gap")
    ax.legend(loc="upper right")
    ax.grid(axis="y", alpha=0.25)
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def _text_page(pdf: PdfPages, title: str, body: list[str]) -> None:
    fig = plt.figure(figsize=(8.5, 11))
    fig.patch.set_facecolor("white")
    fig.text(0.08, 0.94, title, fontsize=16, weight="bold")
    y = 0.9
    for para in body:
        wrapped = textwrap.fill(para, width=100)
        fig.text(0.08, y, wrapped, fontsize=10.5, va="top")
        y -= 0.04 * (wrapped.count("\n") + 1) + 0.02
    plt.axis("off")
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def _build_report(pdf_path: Path, rollup: dict) -> None:
    models = _phase6_models(rollup)

    with PdfPages(pdf_path) as pdf:
        _title_page(pdf)
        _timeline_page(pdf)
        _rates_page(pdf, models)
        _stacked_outcomes_page(pdf, models)
        _phase4_oracle_page(pdf)
        _mechanism_page(pdf)
        _text_page(
            pdf,
            "Methods and Validity",
            [
                "All Phase 6 cells used identical frozen configuration from PRE_PHASE6.md: k=5 runs per model, 20-turn budget, "
                "build_check enabled, and oracle grading under the recovering-lag profile (20s downstream toxic, 10 trials).",
                "Classifier labels were recorded for diagnostics only and never used for scoring; resolution rates use oracle verdicts only.",
                "Delivery and rerun discipline was pre-committed before outcomes: no reruns of capability/build/no-patch failures; "
                "only infra failures were eligible. This preserved measurement integrity across the sweep.",
                "Gemini-3.1-Pro was explicitly held out for non-comparable delivery behavior under the shared prompt; this is reported as exclusion, not scored zero.",
            ],
        )
        _text_page(
            pdf,
            "Key Findings and Scope",
            [
                "Primary empirical result: three-step capability gradient on one bug under identical conditions: "
                "0% (Haiku/Gemini-2.5), 40% (Opus/GPT-4.1), 100% (GPT-5.5).",
                "Mechanistic contribution: Opus FAIL LSN patches and GPT-5.5 PASS LSN patches diverge on one ordering detail "
                "(in-statement vs post-commit WAL capture), confirmed by patch inspection on both sides.",
                "Scope guardrail: this supports a claim about the stale-read archetype and this mechanism family, "
                "not a general ranking of model families on all distributed debugging tasks.",
                "Ceiling limitation: GPT-5.5 saturated this archetype at 5/5, so stale-read no longer discriminates above that level. "
                "Future work should add harder archetypes to continue frontier separation.",
            ],
        )
        _text_page(
            pdf,
            "Artifact Index",
            [
                "Phase 4 canonical: archetype-a/phase_4_report_6.md, PHASE4_CLOSE.md, PHASE4_CONSTRAINTS.md.",
                "Phase 5 gating anchor: phase_5_report_13.md and PRE_PHASE6.md.",
                "Phase 6 canonical: phase_6_report.md and archetype-d-stale-read/phase6_cells/phase6_headline_rollup.json.",
                "Mechanistic diffs: archetype-d-stale-read/phase6_cells/gpt-5.5/PARTIAL_PASS_DIFF.md and "
                "archetype-d-stale-read/phase6_cells/opus-4.8/OPUS_P3_DIFF.md.",
            ],
        )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate final paper-style PDF report.")
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "reports" / "final_research_report.pdf",
        help="Output PDF path.",
    )
    args = parser.parse_args()

    rollup_path = ROOT / "archetype-d-stale-read" / "phase6_cells" / "phase6_headline_rollup.json"
    rollup = _read_json(rollup_path)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    _build_report(args.out, rollup)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
